#!/bin/sh
set -e

case $BLOCK_BUTTON in
	1) setsid -f "$TERMINAL" -e alsamixer & ;;
	2) amixer sset Master toggle ;;
	4) amixer sset Master 5%+ >/dev/null 2>/dev/null ;;
	5) amixer sset Master 5%- >/dev/null 2>/dev/null ;;
	3) pgrep -x dunst >/dev/null && notify-send "📢 Volume module" "\- Shows volume 🔊, 🔇 if muted.
- Middle click to mute.
- Scroll to change." ;;
    6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

volstat="$(LC_ALL=C pactl list sinks | sed -n '/RUNNING/,/Volume/p')"
vol="$(pamixer --get-volume-human)"
[ "$vol" = "muted" ] && printf "🔇\\n" && exit
# vol=${vol%\%}
# if [ "$vol" -gt "70" ]; then
# 	icon="🔊"
# elif [ "$vol" -lt "30" ]; then
# 	icon="🔈"
# else
# 	icon="🔉"
# fi

info="🅥 $vol"
if [ -f "$HOME/.cache/wal/colors-wal-dwmblocks.sh" ]; then
    source "$HOME/.cache/wal/colors-wal-dwmblocks.sh"
    display "$info"
else
    echo "$info"
fi
