# dataviz: common aesthetics

```{r echo = FALSE, message = FALSE}
# run setup script
source("_common.R")
library(forcats)
library(patchwork)
library(lubridate)
library("showtext")
knitr::opts_chunk$set(echo = T, message = F, warning = F, error = F,
                      results = "asis", dpi = 210, dev = "pdf",
                      fig.showtext = TRUE)
```

(ref:common-aesthetics) Commonly used aesthetics in data visualization:
position, shape, size, color, line width, line type. Some of these aesthetics
can represent both continuous and discrete data (position, size, line width,
color) while others can usually only represent discrete data (shape, line
type).

```{r common-aesthetics, fig.width = 6, fig.asp = 0.45, fig.cap = '(ref:common-aesthetics)'}
aes_pos <- ggdraw() +
    geom_segment(
        data = data.frame(x    = c(0,   0.5),
                          y    = c(0.5, 0),
                          xend = c(1,   0.5),
                          yend = c(0.5, 1)),
        mapping = aes(x = x, y = y, xend = xend, yend = yend),
        arrow = arrow(length = grid::unit(12, "pt")), size = .75
    ) +
    draw_text(
        c("x", "y"),
        x = c(1, 0.5), y = c(0.5, 1),
        hjust = c(-0.8, 0.3), vjust = c(0.3, -0.8),
        size = 14, family = "serif") +
    coord_cartesian(xlim = c(-.2, 1.2), ylim = c(-.2, 1.2))

aes_color <- ggdraw() +
    geom_tile(
        data = data.frame(x = 0.15 + .2333 * (0:3)),
        aes(x, y = .5, fill = factor(x)), width = .2, height = .6
    ) +
    scale_fill_OkabeIto(guide = "none")

aes_shape <- ggdraw() +
    geom_point(
        data = data.frame(x = (.5 + 0:3) / 4),
        aes(x, y = .5, shape = factor(x)), size = 8, fill = "grey80"
    ) +
    scale_shape_manual(values = 21:24)

aes_size <- ggdraw() +
    geom_point(
        data = data.frame(x = (.5 + 0:3) / 4),
        aes(x, y = .5, size = factor(x)), shape = 21, fill = "grey80"
    ) +
    scale_size_manual(values = c(2, 5, 8, 11))


aes_lwd <- ggdraw() +
    geom_segment(
        data = data.frame(
            x = rep(0.05, 4),
            y = (1.5 + 0:3) / 6,
            xend = rep(0.95, 4),
            yend = (1.5 + 0:3) / 6,
            size = 4:1
        ),
        aes(x = x, y = y, xend = xend, yend = yend, size = size)
    ) +
    scale_size_identity()

aes_ltp <- ggdraw() +
    geom_segment(
        data = data.frame(
            x = rep(0.05, 4),
            xend = rep(0.95, 4),
            y = (1.5 + 0:3) / 6,
            yend = (1.5 + 0:3) / 6,
            linetype = 4:1
        ),
        aes(x = x, y = y, xend = xend, yend = yend, linetype = linetype), size = 1
    ) +
    scale_linetype_identity()


plot_grid(aes_pos, aes_shape, aes_size,
    aes_color, aes_lwd, aes_ltp,
    ncol = 3,
    labels = c("position", "shape", "size", "color", "line width", "line type"),
    label_fontfamily = "serif", label_size = 14,
    label_x = 0.05, label_y = 0.95, hjust = 0, vjust = 1
)
```
